'use client';

import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ReferenceDot, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CalendarDays, ClipboardList, PackageX, Pencil, Plus, RotateCcw, Star, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { useRouter } from 'next/navigation';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Separator } from '@/components/ui/separator';
import { Skeleton } from '@/components/ui/skeleton';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { InfoTooltip } from '@/components/ui/info-tooltip';
import { EventFormDialog, type EditingEvent } from '@/components/events/event-form-dialog';
import { buildDailyDeltas, calculatePeriodComparison, sortObservations } from '@/domain/inventory/calculations';
import type { InventoryValueBreakdown, SkuAnalysis, StockObservation } from '@/domain/inventory/types';
import { formatMoney, formatNumber, formatSigned } from '@/lib/format';
import { formatKstDate } from '@/lib/date';
import { riskBadgeVariant, analysisStatusText, dataReliabilityClassName, dataReliabilityLevel, dataReliabilityText, humanizeTagText, localizeReason, isB2BTag, isBasisWindowTag, isEstimateCaveatTag, isObservedDateTag, isSoldOutTag, isStaleDepletionTag } from '@/lib/status';
import { eventTypeText } from '@/lib/event-types';
import { useI18n } from '@/components/i18n/i18n-provider';
import { format } from '@/lib/i18n/locales';
import type { Messages } from '@/lib/i18n/messages';
import type { SkuDescriptor } from '@/domain/inventory/read-model';
import type { ReorderSuggestion } from '@/domain/reorder/reorder';
import { ReorderPanel, type Turnover30 } from './reorder-panel';
import { ReliabilityInfo } from '@/components/ui/reliability-info';
import { Paged } from '@/components/ui/paged';

interface SkuDetailResponse {
  descriptor: SkuDescriptor;
  analysis: SkuAnalysis;
  valueBreakdown: InventoryValueBreakdown;
  observations: StockObservation[];
  expirationLots: { lot: string; expirationDate: string }[];
  reorder?: ReorderSuggestion | null;
  turnover30?: Turnover30 | null;
}

interface EventItem {
  id: string;
  eventType: string;
  quantity: number | null;
  note: string;
  eventDate: string;
  endDate: string | null;
  title: string | null;
  scheduleId?: string | null;
  isAutoGenerated: boolean;
  createdBy: { name: string };
}

interface SkuDetailSheetProps {
  skuId: string | null;
  asOfDate: string;
  fromDate: string | null;
  isAdmin: boolean;
  isFavorited: boolean;
  onToggleFavorite: (skuId: string, next: boolean) => void;
  onOpenChange: (open: boolean) => void;
}

export function SkuDetailSheet({ skuId, asOfDate, fromDate, isAdmin, isFavorited, onToggleFavorite, onOpenChange }: SkuDetailSheetProps) {
  const { m, locale } = useI18n();
  const t = m.inventory.detail;
  const qty = (n: number) => format(t.qty, { count: formatNumber(n) });
  const [detail, setDetail] = useState<SkuDetailResponse | null>(null);
  const [events, setEvents] = useState<EventItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [rangeDays, setRangeDays] = useState<30 | 60 | 90>(30);
  const [formOpen, setFormOpen] = useState(false);
  const [formPrefill, setFormPrefill] = useState<{ quantity?: number; date?: string }>({});
  const [editingEvent, setEditingEvent] = useState<EditingEvent | null>(null);
  const [editingThresholds, setEditingThresholds] = useState(false);
  const [dangerInput, setDangerInput] = useState('');
  const [warningInput, setWarningInput] = useState('');
  const [savingThresholds, setSavingThresholds] = useState(false);
  const [togglingB2B, setTogglingB2B] = useState(false);
  const [specialNoteInput, setSpecialNoteInput] = useState<string | null>(null);
  const [savingSpecialNote, setSavingSpecialNote] = useState(false);
  const router = useRouter();

  async function reload() {
    if (!skuId) return;
    setLoading(true);
    try {
      const [detailRes, eventsRes] = await Promise.all([
        fetch(`/api/sku/${skuId}?asOf=${asOfDate}`),
        fetch(`/api/events?skuId=${skuId}`),
      ]);
      if (detailRes.ok) setDetail(await detailRes.json());
      if (eventsRes.ok) {
        const body = await eventsRes.json();
        setEvents(body.events);
      }
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (skuId) reload();
    else {
      setDetail(null);
      setEvents([]);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [skuId, asOfDate]);

  const chartData = useMemo(() => {
    if (!detail) return [];
    const cutoff = new Date(asOfDate);
    cutoff.setDate(cutoff.getDate() - rangeDays);
    const cutoffStr = fromDate ?? cutoff.toISOString().slice(0, 10);
    return detail.observations.filter((o) => o.date >= cutoffStr).map((o) => ({ date: o.date, availableStock: o.availableStock }));
  }, [detail, rangeDays, asOfDate, fromDate]);

  const periodMetrics = useMemo(() => {
    if (!detail || !fromDate) return null;
    return calculatePeriodComparison(detail.observations, fromDate, asOfDate);
  }, [detail, fromDate, asOfDate]);

  const eventMarkers = useMemo(() => {
    if (chartData.length === 0) return [];
    const dates = new Set(chartData.map((d) => d.date));
    return events
      .filter((e) => dates.has(formatKstDate(e.eventDate)))
      .map((e) => {
        const eventKstDate = formatKstDate(e.eventDate);
        const point = chartData.find((d) => d.date === eventKstDate);
        return point ? { date: eventKstDate, availableStock: point.availableStock, note: e.note, eventType: e.eventType } : null;
      })
      .filter((v): v is { date: string; availableStock: number; note: string; eventType: string } => v !== null);
  }, [chartData, events]);

  // 이 SKU에 관측치가 이번 한 건뿐이면(과거 이력 없음) 현재 표시된 재고는 처음 인식된 그대로의
  // 초기재고다 — 소진/증가 계산 대상이 아니므로 계산 로직은 이미 이를 건드리지 않고, 여기서는
  // 그 사실을 사용자에게 보이는 태그로만 알려준다.
  const isInitialObservation = useMemo(() => {
    if (!detail) return false;
    return sortObservations(detail.observations).length <= 1;
  }, [detail]);

  async function toggleB2B(checked: boolean) {
    if (!skuId) return;
    setTogglingB2B(true);
    try {
      const res = await fetch(`/api/sku/${skuId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isB2B: checked }),
      });
      if (!res.ok) throw new Error();
      toast.success(checked ? t.b2bOn : t.b2bOff);
      reload();
      // 대시보드의 특수 관리 재고 표·운영 유형 카드가 바로 따라오도록 서버 데이터를 다시 읽는다.
      router.refresh();
    } catch {
      toast.error(t.changeFailed);
    } finally {
      setTogglingB2B(false);
    }
  }

  async function saveSpecialNote() {
    if (!skuId || specialNoteInput === null) return;
    if (specialNoteInput.trim() === (detail?.descriptor.specialNote ?? '')) {
      setSpecialNoteInput(null);
      return;
    }
    setSavingSpecialNote(true);
    try {
      const res = await fetch(`/api/sku/${skuId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ specialNote: specialNoteInput }),
      });
      if (!res.ok) throw new Error();
      toast.success(t.specialNoteSaved);
      setSpecialNoteInput(null);
      reload();
      router.refresh();
    } catch {
      toast.error(t.saveFailed);
    } finally {
      setSavingSpecialNote(false);
    }
  }

  const unclassifiedIncreases = useMemo(() => {
    if (!detail) return [];
    const sorted = sortObservations(detail.observations);
    const deltas = buildDailyDeltas(sorted);
    return deltas
      .filter((d) => d.increase > 0)
      .filter((d) => !events.some((e) => formatKstDate(e.eventDate) >= d.fromDate && formatKstDate(e.eventDate) <= d.toDate))
      .slice(-3)
      .reverse();
  }, [detail, events]);

  function startEditingThresholds() {
    if (!detail) return;
    setDangerInput(String(detail.analysis.riskThresholds.dangerQty));
    setWarningInput(String(detail.analysis.riskThresholds.warningQty));
    setEditingThresholds(true);
  }

  async function saveThresholds() {
    if (!skuId) return;
    const dangerQty = Number(dangerInput);
    const warningQty = Number(warningInput);
    if (!Number.isInteger(dangerQty) || dangerQty < 0 || !Number.isInteger(warningQty) || warningQty < 0) {
      toast.error(t.integerOnly);
      return;
    }
    setSavingThresholds(true);
    try {
      const res = await fetch(`/api/sku/${skuId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ manualDangerQty: dangerQty, manualWarningQty: warningQty }),
      });
      if (!res.ok) throw new Error();
      toast.success(t.thresholdsSaved);
      setEditingThresholds(false);
      reload();
    } catch {
      toast.error(t.saveFailed);
    } finally {
      setSavingThresholds(false);
    }
  }

  async function resetThresholds() {
    if (!skuId) return;
    setSavingThresholds(true);
    try {
      const res = await fetch(`/api/sku/${skuId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ manualDangerQty: null, manualWarningQty: null }),
      });
      if (!res.ok) throw new Error();
      toast.success(t.revertedAuto);
      setEditingThresholds(false);
      reload();
    } catch {
      toast.error(t.revertFailed);
    } finally {
      setSavingThresholds(false);
    }
  }

  async function handleDeleteEvent(id: string) {
    if (!confirm(t.deleteEventConfirm)) return;
    const res = await fetch(`/api/events/${id}`, { method: 'DELETE' });
    if (res.ok) {
      toast.success(t.deleted);
      reload();
    } else {
      toast.error(t.deleteFailed);
    }
  }

  return (
    <Sheet open={!!skuId} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full overflow-y-auto sm:max-w-[520px]">
        {loading && !detail && (
          <div className="space-y-6 p-5">
            <div className="space-y-2">
              <Skeleton className="h-5 w-2/3" />
              <Skeleton className="h-4 w-1/3" />
            </div>
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <div key={i} className="space-y-1.5">
                  <Skeleton className="h-3 w-16" />
                  <Skeleton className="h-4 w-20" />
                </div>
              ))}
            </div>
            <Skeleton className="h-56 w-full" />
            <div className="space-y-2">
              <Skeleton className="h-16 w-full" />
              <Skeleton className="h-16 w-full" />
            </div>
          </div>
        )}
        {detail && (
          <>
            <SheetHeader>
              <div className="flex flex-wrap items-center gap-2">
                <button
                  type="button"
                  onClick={() => skuId && onToggleFavorite(skuId, !isFavorited)}
                  className="shrink-0 rounded-md p-1 text-muted-foreground transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  aria-label={isFavorited ? t.favoriteRemove : t.favoriteAdd}
                  aria-pressed={isFavorited}
                >
                  <Star className={isFavorited ? 'size-4 fill-amber-400 text-amber-400' : 'size-4'} aria-hidden="true" />
                </button>
                <SheetTitle>{detail.descriptor.productName}</SheetTitle>
                {detail.descriptor.isSoldOut && (
                  <>
                    <Badge variant="soldout" className="gap-1">
                      <PackageX className="size-3" aria-hidden="true" />
                      {m.inventory.row.soldOut}
                    </Badge>
                    <InfoTooltip>
                      {t.soldOutTip}
                    </InfoTooltip>
                  </>
                )}
                {!detail.descriptor.isSoldOut && !detail.descriptor.isB2B && (
                  <Badge variant={riskBadgeVariant(detail.analysis.thresholdRisk.level)}>{analysisStatusText(detail.analysis, m.domain)}</Badge>
                )}
                {detail.descriptor.isB2B && (
                  <>
                    <Badge variant="outline" className="gap-1">
                      <ClipboardList className="size-3" aria-hidden="true" />
                      {m.inventory.special}
                    </Badge>
                    <InfoTooltip>
                      {t.b2bTip}
                    </InfoTooltip>
                  </>
                )}
              </div>
              <SheetDescription>
                {detail.descriptor.productCode} · {detail.descriptor.warehouseName}
                {detail.descriptor.option ? ` · ${detail.descriptor.option}` : ''}
                {t.firstSeen}
                {formatKstDate(detail.descriptor.firstSeenDate)}
                {' '}
                <span className={`rounded-md bg-muted px-2 py-0.5 text-xs font-medium ${dataReliabilityClassName(dataReliabilityLevel(detail.analysis))}`}>
                  {dataReliabilityText(dataReliabilityLevel(detail.analysis), m.domain)}
                </span>
                <ReliabilityInfo reliability={detail.analysis.reliability} className="ml-1 align-middle" />
              </SheetDescription>
            </SheetHeader>

            <div className="space-y-5 p-4 sm:p-5">
              {(detail.analysis.tags.length > 0 || isInitialObservation) && (
                <div className="flex flex-wrap gap-1.5">
                  {isInitialObservation && (
                    <span className="rounded-md bg-status-increase-bg px-2 py-0.5 text-xs text-status-increase">{t.initialStock}</span>
                  )}
                  {detail.analysis.tags.filter((tag) => !isObservedDateTag(tag) && !isEstimateCaveatTag(tag) && !isBasisWindowTag(tag) && !isSoldOutTag(tag) && !isStaleDepletionTag(tag) && !isB2BTag(tag)).map((tag) => (
                    <span key={tag} className="rounded-md bg-muted px-2 py-0.5 text-xs text-muted-foreground">{humanizeTagText(tag, m.domain)}</span>
                  ))}
                </div>
              )}

              <section className="rounded-xl border bg-muted/30 p-3">
                <h3 className="mb-2 text-xs font-semibold">{t.extraInfo}</h3>
                <div className="space-y-2">
                  <div>
                    <div className="text-xs text-muted-foreground">{t.lots}</div>
                    <div className="mt-1 flex flex-wrap gap-1.5">
                      {detail.expirationLots.length === 0 ? (
                        <span className="text-sm text-muted-foreground">{t.noLots}</span>
                      ) : (
                        detail.expirationLots.map((lot) => (
                          <span key={lot.lot} className="rounded-md bg-card px-2 py-0.5 text-xs">
                            {lot.lot} {formatKstDate(lot.expirationDate)}
                          </span>
                        ))
                      )}
                    </div>
                  </div>
                  <div className="grid grid-cols-3 gap-x-3 gap-y-1 text-sm">
                    <Field label="EA/BOX" value={detail.descriptor.eaPerBox !== null ? qty(detail.descriptor.eaPerBox) : t.notRegistered} />
                    <Field label="EA/PLT" value={detail.descriptor.eaPerPallet !== null ? qty(detail.descriptor.eaPerPallet) : t.notRegistered} />
                    <Field label={t.barcode} value={detail.descriptor.packagingBarcode ?? t.notRegistered} />
                  </div>
                </div>
              </section>

              <section className="grid grid-cols-2 gap-2">
                <MetricCard label={detail.descriptor.isSoldOut ? t.lastObservedStock : t.observedStock} value={qty(detail.analysis.latest.availableStock)} />
                <MetricCard label={detail.descriptor.isSoldOut ? t.lastObservedValue : t.observedValue} value={detail.analysis.latest.valuationKnown === false ? t.unknownCost : formatMoney(detail.valueBreakdown.normalStockValue, locale)} />
                <MetricCard label={t.coverage} value={detail.analysis.coverage.coverageDays === null ? t.notComputable : format(t.shippingDays, { days: formatNumber(detail.analysis.coverage.coverageDays) })} />
                <MetricCard
                  label={t.stockoutDate}
                  value={detail.analysis.forecast.expectedStockoutDate ? formatKstDate(detail.analysis.forecast.expectedStockoutDate) : (detail.analysis.operating?.reason ? localizeReason(detail.analysis.operating.reason, m.domain) : t.notComputable)}
                />
              </section>

              {!detail.descriptor.isSoldOut && (
                <ReorderPanel
                  key={detail.descriptor.skuId}
                  skuId={detail.descriptor.skuId}
                  reorder={detail.reorder}
                  turnover30={detail.turnover30}
                  supplierId={detail.descriptor.supplierId}
                  overrides={detail.descriptor.reorderOverrides}
                  canEdit={isAdmin}
                  onSaved={reload}
                />
              )}

              <section className="rounded-xl border bg-muted/30 p-3">
                <div className="mb-2 flex items-center justify-between">
                  <h3 className="text-xs font-semibold">{t.thresholds}</h3>
                  {isAdmin && !editingThresholds && (
                    <Button variant="ghost" size="sm" className="h-6 px-2 text-[11px]" onClick={startEditingThresholds}>
                      <Pencil className="size-3" /> {t.edit}
                    </Button>
                  )}
                </div>
                {editingThresholds ? (
                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-xs">
                      <label htmlFor="danger-qty-input" className="w-16 text-muted-foreground">{t.dangerQty}</label>
                      <Input id="danger-qty-input" value={dangerInput} onChange={(e) => setDangerInput(e.target.value)} inputMode="numeric" className="h-8 text-xs" />
                    </div>
                    <div className="flex items-center gap-2 text-xs">
                      <label htmlFor="warning-qty-input" className="w-16 text-muted-foreground">{t.warningQty}</label>
                      <Input id="warning-qty-input" value={warningInput} onChange={(e) => setWarningInput(e.target.value)} inputMode="numeric" className="h-8 text-xs" />
                    </div>
                    <div className="flex flex-wrap items-center gap-2 pt-1">
                      <Button size="sm" className="h-7 text-xs" onClick={saveThresholds} disabled={savingThresholds}>
                        {t.save}
                      </Button>
                      <Button size="sm" variant="outline" className="h-7 text-xs" onClick={resetThresholds} disabled={savingThresholds}>
                        <RotateCcw className="size-3" /> {t.revertAuto}
                      </Button>
                      <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={() => setEditingThresholds(false)} disabled={savingThresholds}>
                        {t.cancel}
                      </Button>
                    </div>
                  </div>
                ) : (
                  <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-sm">
                    <Field label={t.dangerQty} value={qty(detail.analysis.riskThresholds.dangerQty)} />
                    <Field label={t.warningQty} value={qty(detail.analysis.riskThresholds.warningQty)} />
                  </div>
                )}
                {!editingThresholds && <p className="mt-2 text-[11px] text-muted-foreground">{thresholdSourceLabel(detail.analysis.riskThresholds.source, t)}</p>}
              </section>

              {isAdmin ? (
                <section className="rounded-xl border bg-muted/30 p-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5">
                      <ClipboardList className="size-3.5 text-muted-foreground" aria-hidden="true" />
                      <span className="text-xs font-semibold">{t.b2bTitle}</span>
                      <InfoTooltip>{t.b2bSwitchTip}</InfoTooltip>
                    </div>
                    <Switch checked={detail.descriptor.isB2B} onCheckedChange={toggleB2B} disabled={togglingB2B} aria-label={t.b2bSwitch} />
                  </div>
                  {detail.descriptor.isB2B && (
                    <form
                      className="mt-2.5 flex items-center gap-2"
                      onSubmit={(e) => {
                        e.preventDefault();
                        saveSpecialNote();
                      }}
                    >
                      <Input
                        value={specialNoteInput ?? detail.descriptor.specialNote ?? ''}
                        onChange={(e) => setSpecialNoteInput(e.target.value)}
                        placeholder={t.specialNotePlaceholder}
                        aria-label={t.specialNote}
                        maxLength={200}
                        className="h-8 bg-background text-xs"
                      />
                      <Button type="submit" size="sm" variant="outline" className="h-8 shrink-0" disabled={specialNoteInput === null || savingSpecialNote}>
                        {t.save}
                      </Button>
                    </form>
                  )}
                </section>
              ) : (
                detail.descriptor.isB2B &&
                detail.descriptor.specialNote && (
                  <section className="rounded-xl border bg-muted/30 p-3 text-xs">
                    <span className="font-semibold">{t.specialNote}</span>
                    <p className="mt-1 text-muted-foreground">{detail.descriptor.specialNote}</p>
                  </section>
                )
              )}

              {fromDate && (
                <section className="rounded-xl border bg-muted/30 p-3">
                  <div className="mb-3 flex items-center justify-between">
                    <h3 className="text-xs font-semibold">{t.period}</h3>
                    <span className="text-[11px] text-muted-foreground">
                      {periodMetrics ? format(t.periodObserved, { from: periodMetrics.actualStartDate.slice(5), to: periodMetrics.actualEndDate.slice(5) }) : `${fromDate.slice(5)} — ${asOfDate.slice(5)}`}
                    </span>
                  </div>
                  {periodMetrics ? (
                    <div className="grid grid-cols-2 gap-x-4 gap-y-3 text-sm">
                      <Field label={t.netChange} value={format(t.qty, { count: formatSigned(periodMetrics.netChange) })} />
                      <Field label={t.periodDepletion} value={qty(periodMetrics.totalDepletion)} />
                      <Field label={t.periodIncrease} value={qty(periodMetrics.totalIncrease)} />
                      <Field label={t.periodInbound} value={qty(periodMetrics.totalInboundQuantity ?? 0)} />
                      <Field label={t.periodAvg} value={fmtRate(periodMetrics.averageDailyDepletion, t, t.unitCalendar)} />
                    </div>
                  ) : <p className="text-xs text-muted-foreground">{t.periodShort}</p>}
                </section>
              )}

              <Separator />

              <section>
                <h3 className="mb-2 text-sm font-semibold">{t.trendTitle}</h3><p className="mb-3 text-xs text-muted-foreground">{format(t.trendNote, { reason: detail.analysis.operating?.reason ? localizeReason(detail.analysis.operating.reason, m.domain) : t.trendReference, window: detail.analysis.operating?.basisWindowDays ?? '—', observed: detail.analysis.operating?.observedShippingDays ?? 0, date: detail.analysis.latest.date })}</p>
                <div className="grid grid-cols-2 gap-x-4 gap-y-3 text-sm">
                  <Field label={t.avg7} value={fmtRate(detail.analysis.window7.averageDailyDepletion, t)} />
                  <Field label={t.inbound7} value={qty(detail.analysis.window7.totalInboundQuantity ?? 0)} />
                  <Field label={t.avg14} value={fmtRate(detail.analysis.window14.averageDailyDepletion, t)} />
                  <Field label={t.avg30} value={fmtRate(detail.analysis.window30.averageDailyDepletion, t)} />
                  <Field label={t.accel} value={accelerationText(detail.analysis, t)} />
                  <Field label={t.confidence} value={confidenceLabel(detail.analysis.forecast.confidence, t)} />
                </div>
              </section>

              <Separator />

              <section>
                <div className="mb-2 flex items-center justify-between">
                  <h3 className="text-sm font-semibold">{t.stockTrend}</h3>
                  {!fromDate && <Tabs value={String(rangeDays)} onValueChange={(v) => setRangeDays(Number(v) as 30 | 60 | 90)}>
                    <TabsList>
                      <TabsTrigger value="30">{format(t.days, { days: 30 })}</TabsTrigger>
                      <TabsTrigger value="60">{format(t.days, { days: 60 })}</TabsTrigger>
                      <TabsTrigger value="90">{format(t.days, { days: 90 })}</TabsTrigger>
                    </TabsList>
                  </Tabs>}
                </div>
                <div className="h-48">
                  {chartData.length < 2 ? (
                    <div className="flex h-full items-center justify-center text-sm text-muted-foreground">{t.accumulating}</div>
                  ) : (
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 0 }}>
                        <defs>
                          <linearGradient id="stockGradient" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="0%" stopColor="var(--color-chart-1)" stopOpacity={0.35} />
                            <stop offset="100%" stopColor="var(--color-chart-1)" stopOpacity={0} />
                          </linearGradient>
                        </defs>
                        <CartesianGrid stroke="var(--color-border)" vertical={false} />
                        <XAxis dataKey="date" tickFormatter={(d: string) => formatKstDate(d).slice(5)} fontSize={11} stroke="var(--color-muted-foreground)" tickLine={false} axisLine={false} />
                        <YAxis width={44} fontSize={11} stroke="var(--color-muted-foreground)" tickLine={false} axisLine={false} />
                        <Tooltip labelFormatter={(d) => formatKstDate(String(d))} formatter={(v) => [qty(Number(v)), t.availableStock]} contentStyle={{ fontSize: 12, borderRadius: 8 }} />
                        <Area type="monotone" dataKey="availableStock" stroke="var(--color-chart-1)" fill="url(#stockGradient)" strokeWidth={2} />
                        {eventMarkers.map((m, i) => (
                          <ReferenceDot key={i} x={m.date} y={m.availableStock} r={4} fill="var(--color-chart-4)" stroke="var(--color-background)" />
                        ))}
                      </AreaChart>
                    </ResponsiveContainer>
                  )}
                </div>
              </section>

              {unclassifiedIncreases.length > 0 && (
                <div className="space-y-2 rounded-md border border-status-increase/30 bg-status-increase-bg p-3">
                  <div className="text-xs font-medium text-status-increase">{t.increaseDetected}</div>
                  <Paged items={unclassifiedIncreases} pagerClassName="mt-2">
                    {(pageItems) => (
                      <>
                        {pageItems.map((d, i) => (
                          <div key={i} className="flex items-center justify-between text-xs">
                            <span>
                              {format(t.increaseOn, { date: formatKstDate(d.toDate), qty: formatNumber(d.increase) })}
                            </span>
                            <Button
                              size="sm"
                              variant="outline"
                              className="h-6 text-[11px]"
                              onClick={() => {
                                setEditingEvent(null);
                                setFormPrefill({ quantity: d.increase, date: d.toDate });
                                setFormOpen(true);
                              }}
                            >
                              {t.classify}
                            </Button>
                          </div>
                        ))}
                      </>
                    )}
                  </Paged>
                </div>
              )}

              <Separator />

              <section>
                <div className="mb-2 flex items-center justify-between">
                  <h3 className="text-sm font-semibold">{t.events}</h3>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      setEditingEvent(null);
                      setFormPrefill({});
                      setFormOpen(true);
                    }}
                  >
                    <Plus className="size-3.5" /> {t.add}
                  </Button>
                </div>
                <div className="space-y-2">
                  {events.length === 0 && <p className="text-sm text-muted-foreground">{t.noEvents}</p>}
                  <Paged items={events} pagerClassName="mt-2">
                    {(pageItems) => (
                      <>
                        {pageItems.map((e) => {
                          const startLabel = formatKstDate(e.eventDate);
                          const endLabel = e.endDate ? formatKstDate(e.endDate) : null;
                          const dateLabel = endLabel && endLabel !== startLabel ? `${startLabel} ~ ${endLabel}` : startLabel;
                          return (
                            <div key={e.id} className="rounded-md border p-2.5 text-sm">
                              <div className="flex items-center justify-between gap-2">
                                <div className="flex min-w-0 items-center gap-2">
                                  <Badge variant="outline" className="shrink-0">{eventTypeText(e.eventType, m.domain.eventTypes)}</Badge>
                                  {e.scheduleId && (
                                    <span className="inline-flex shrink-0 items-center gap-1 text-[11px] text-muted-foreground">
                                      <CalendarDays className="size-3" aria-hidden="true" />
                                      {t.calendarLinked}
                                      <InfoTooltip>{t.calendarLinkedTip}</InfoTooltip>
                                    </span>
                                  )}
                                  {e.title && <span className="truncate text-sm font-semibold">{e.title}</span>}
                                  {e.quantity !== null && <span className="shrink-0 text-xs text-muted-foreground">{format(t.qty, { count: formatSigned(e.quantity) })}</span>}
                                </div>
                                <div className="flex shrink-0 items-center gap-2 text-xs text-muted-foreground">
                                  {dateLabel}
                                  <button
                                    onClick={() => {
                                      setEditingEvent({
                                        id: e.id,
                                        eventType: e.eventType as EditingEvent['eventType'],
                                        quantity: e.quantity,
                                        title: e.title,
                                        note: e.note,
                                        eventDate: e.eventDate,
                                        endDate: e.endDate,
                                      });
                                      setFormOpen(true);
                                    }}
                                    className="rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                                    aria-label={t.edit}
                                  >
                                    <Pencil className="size-3.5" />
                                  </button>
                                  <button
                                    onClick={() => handleDeleteEvent(e.id)}
                                    className="rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-destructive/10 hover:text-destructive focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                                    aria-label={t.delete}
                                  >
                                    <Trash2 className="size-3.5" />
                                  </button>
                                </div>
                              </div>
                              <p className="mt-1 text-sm">{e.note}</p>
                              <p className="mt-1 text-[11px] text-muted-foreground">{format(t.author, { name: e.createdBy.name })}</p>
                            </div>
                          );
                        })}
                      </>
                    )}
                  </Paged>
                </div>
              </section>
            </div>

            <EventFormDialog
              open={formOpen}
              onOpenChange={(open) => {
                setFormOpen(open);
                if (!open) setEditingEvent(null);
              }}
              warehouseId={detail.descriptor.warehouseId}
              skuId={detail.descriptor.skuId}
              skuLabel={detail.descriptor.productName}
              defaultQuantity={formPrefill.quantity}
              defaultEventDate={formPrefill.date}
              editingEvent={editingEvent}
              onCreated={reload}
            />
          </>
        )}
      </SheetContent>
    </Sheet>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className="font-medium tabular-nums">{value}</div>
    </div>
  );
}

function MetricCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border bg-card p-3">
      <div className="text-[11px] text-muted-foreground">{label}</div>
      <div className="mt-1 text-base font-semibold tracking-tight tabular-nums">{value}</div>
    </div>
  );
}

type DetailText = Messages['inventory']['detail'];

function fmtRate(value: number | null, t: DetailText, unit = t.unitShipping): string {
  return value === null ? t.notComputable : format(t.rate, { value: formatNumber(value), unit });
}

function accelerationText(analysis: SkuAnalysis, t: DetailText): string {
  const { trend, accelerationRatePercent } = analysis.acceleration;
  if (trend === null) return t.accumulating;
  if (trend === 'NEW_DEPLETION') return t.newDepletion;
  if (trend === 'ACCELERATING') return format(t.accelerating, { percent: Math.round(accelerationRatePercent ?? 0) });
  if (trend === 'DECELERATING') return format(t.decelerating, { percent: Math.round(accelerationRatePercent ?? 0) });
  return t.stable;
}

function confidenceLabel(confidence: SkuAnalysis['forecast']['confidence'], t: DetailText): string {
  return confidence === 'HIGH' || confidence === 'MEDIUM' || confidence === 'LOW' ? t.confidenceLevels[confidence] : '-';
}

function thresholdSourceLabel(source: SkuAnalysis['riskThresholds']['source'], t: DetailText): string {
  if (source === 'manual' || source === 'legacy' || source === 'auto') return t.thresholdSource[source];
  return t.thresholdSource.none;
}
